[package]
name = "GUI_RustySnout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
gtk = {version = "0.4.7", package = "gtk4"}
rusqlite = "0.31.0"
glib = "0.10"
